FROM node:18-alpine

WORKDIR /app
COPY package*.json ./
RUN npm install

# Copy the rest of the app
COPY . .

# Build the app for production
RUN npm run build

# Install serve to run the production build
RUN npm install -g serve

# Set environment to production
ENV NODE_ENV=production

# Start command using the production build
CMD ["serve", "-s", "build"]