FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# RUN npm run build

# RUN npm install -g serve

# # Build the React app for development (not production)
# CMD ["serve", "-s", "build"]

CMD ["npm", "start"]